# -*- coding: utf-8 -*-
"""Missing value.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dbb39dpGZpNuSDvx_y-10Z6QRyTLjBJa
"""

#reading the data

import pandas as pd
import numpy as np

nfl_data = pd.read_csv("C:/Users/ARNAV/Desktop/Data analysis practice/missing value/NFLDATA.csv" ,encoding='utf-8')


np.random.seed(0)

nfl_data.sample(5)

missing_values_count = nfl_data.isnull().sum()

missing_values_count[0:10]

total_cells = np.product(nfl_data.shape)
total_missing = missing_values_count.sum()

(total_missing/total_cells) * 100

nfl_data.dropna()

#dropping data with null values

columns_with_na_dropped = nfl_data.dropna(axis=1)
columns_with_na_dropped.head()

#printing number of columns before and after dropping null columns

print("Columns in original dataset: %d \n" % nfl_data.shape[1])
print("Columns with na's dropped: %d" % columns_with_na_dropped.shape[1])

subset_nfl_data = nfl_data.loc[:, 'EPA':'Season'].head()
subset_nfl_data

#replacing all null values with 1

subset_nfl_data.fillna(1)

#fill the missing values with the value that comes just below it using "bfill"

subset_nfl_data.fillna(method = 'bfill', axis=0).fillna(0)

